name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
        gcc: [8,9,10]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-gcc${{ matrix.gcc }}
    env:
      CC:   gcc-${{ matrix.gcc }}
      CXX:  g++-${{ matrix.gcc }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies
      run: |
        sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}

    - name: Compile
      working-directory: examples
      run: make VERBOSE=1

    - name: Run Tests
      working-directory: examples
      run: make test
